name: Model Training Pipeline
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  train-classifier:
    runs-on: gpu-large
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          python scripts/data_processing/solana_etl.py --days 30
          python models/training/pipelines/train_classifier.py \
            --epochs 50 \
            --batch-size 256 \
            --output s3://under-score-models/classifier_v3.pt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TRAINING_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TRAINING_SECRET }}
